README.md
qxmpp.pri
src/base/QXmppCodec.cpp
src/base/QXmppCodec_p.h
src/base/QXmppRtpChannel.cpp

This changes enhances a lot video and audio quality.

Added Opus codec. Added FEC for Vp8 codec.

---

src/base/QXmppMessage.cpp
tests/qxmppmessage/tst_qxmppmessage.cpp

use XEP-0203 instead of XEP-0091, if there have XEP-0203.

fix issue#52

---

src/base/QXmppConstants.cpp
src/base/QXmppConstants_p.h
src/base/QXmppMamIq.cpp
src/base/QXmppMamIq.h
src/base/base.pri
src/client/QXmppMamManager.cpp
src/client/QXmppMamManager.h
src/client/client.pri
tests/qxmppmammanager/qxmppmammanager.pro
tests/qxmppmammanager/tst_qxmppmammanager.cpp
tests/tests.pro

This PR implements _XEP-0313: Message Archive Management_.
QXmpp already has _XEP-0136: Message Archiving_ but XEP-0313 seems to be supported by more servers.

Implement XEP-0313: Message Archive Management

---

doc/xep.doc
src/base/QXmppRosterIq.cpp
src/base/QXmppRosterIq.h
tests/qxmpprosteriq/tst_qxmpprosteriq.cpp

add version attribute to support protocol XEP-0237 Roster Versioning
https://xmpp.org/rfcs/rfc6121.html#roster-versioning
https://xmpp.org/extensions/xep-0237.html

support XEP-0237 Roster Versioning

---

src/client/QXmppOutgoingClient.cpp

I had the problem (company network) where the default port 5222 is blocked.
The DNS record however knows an alternative server, which was not used automatically.
This patch adds the possibility to automatically try the next server when the first fails.
(I hope the check d->sessionStarted is correct)

automatically try next server from DNS SRV record when connection to first can not be established

---

README.md
src/CMakeLists.txt

* add BUILD_SHARED to support library type
* add BUILD_SHARED to README
* add default value hint to README

Support to build both static and shared library

---

doc/xep.doc
src/base/QXmppConstants.cpp
src/base/QXmppConstants_p.h
src/base/QXmppPresence.cpp
src/base/QXmppPresence.h
tests/qxmpppresence/tst_qxmpppresence.cpp

https://xmpp.org/extensions/xep-0319.html

Implement XEP-0319: Last User Interaction in Presence

---

CHANGELOG.md
src/base/QXmppSasl.cpp
src/base/QXmppSasl_p.h
tests/qxmppsasl/tst_qxmppsasl.cpp

I have been able to test SCRAM-SHA-1 against the jabber.at server, does anyone know one which supports SCRAM-SHA-256?

[sasl] add support for SCRAM-SHA-1 and SCRAM-SHA-256

---

README.md

The GuiClient / example 4 has been removed.

README: Remove notice about GuiClient example

---

CHANGELOG.md
doc/xep.doc
src/base/QXmppConstants.cpp
src/base/QXmppConstants_p.h
src/base/QXmppMessage.cpp
src/base/QXmppMessage.h
tests/qxmppmessage/tst_qxmppmessage.cpp

This adds parsing and serialization of spoilers in the QXmppMessage class.

Implement XEP-0382: Spoiler messages

---

doc/xep.doc
src/base/QXmppConstants.cpp
src/base/QXmppMixIq.cpp
src/base/QXmppMixIq.h
tests/qxmppmessage/tst_qxmppmessage.cpp
tests/qxmppmixiq/tst_qxmppmixiq.cpp

The changes in the XEP only affect parts we haven't implemented yet, so
updating was rather easy.

Update implementation of XEP-0369 (v0.14.2) and XEP-0405 (v0.4.0)

---

src/base/QXmppHttpUploadIq.cpp
src/base/QXmppHttpUploadIq.h
src/base/QXmppMixIq.cpp
src/base/QXmppMixIq.h
src/base/QXmppMixItem.cpp
src/base/QXmppMixItem.h
src/base/QXmppRosterIq.cpp
src/base/QXmppRosterIq.h

(Was my fault in most/all cases)

Use QSharedData for all private data classes

---

doc/index.doc
src/CMakeLists.txt
src/base/QXmppStanza.cpp
src/base/QXmppStanza.h
src/client/QXmppUploadRequestManager.cpp
src/client/QXmppUploadRequestManager.h
tests/CMakeLists.txt
tests/qxmppstanza/tst_qxmppstanza.cpp
tests/qxmppuploadrequestmanager/CMakeLists.txt
tests/qxmppuploadrequestmanager/test.svg
tests/qxmppuploadrequestmanager/tst_qxmppuploadrequestmanager.cpp
tests/qxmppuploadrequestmanager/tst_qxmppuploadrequestmanager.qrc

Implement XEP-0363: HTTP File Upload: Error cases / UploadRequestManager

---

examples/example_3_transferHandling/example_3_transferHandling.cpp
examples/example_5_rpcInterface/main.cpp
src/base/QXmppJingleIq.cpp
src/base/QXmppLogger.cpp
src/base/QXmppRtpChannel.cpp
src/base/QXmppSocks.cpp
src/base/QXmppStream.cpp
src/base/QXmppStun.cpp
src/base/QXmppUtils.cpp
src/client/QXmppCallManager.cpp
src/client/QXmppClient.cpp
src/client/QXmppClient.h
src/client/QXmppOutgoingClient.cpp
src/client/QXmppTransferManager.cpp
src/server/QXmppIncomingClient.cpp
src/server/QXmppIncomingServer.cpp
src/server/QXmppOutgoingServer.cpp
src/server/QXmppPasswordChecker.cpp
src/server/QXmppServer.cpp
tests/qxmppcallmanager/tst_qxmppcallmanager.cpp
tests/qxmppiq/tst_qxmppiq.cpp
tests/qxmppjingleiq/tst_qxmppjingleiq.cpp
tests/qxmppmessage/tst_qxmppmessage.cpp
tests/qxmpprosteriq/tst_qxmpprosteriq.cpp
tests/qxmppstanza/tst_qxmppstanza.cpp
tests/qxmpptransfermanager/tst_qxmpptransfermanager.cpp

by using raw string literals, range based loops were possible and auto.

Modernize cpp

---

src/client/QXmppMucManager.cpp

QXmppMucManager: Only return true if actually handled stanza

---

doc/xep.doc
src/base/QXmppConstants.cpp
src/base/QXmppConstants_p.h
src/base/QXmppMessage.cpp
src/base/QXmppMessage.h
tests/qxmppmessage/tst_qxmppmessage.cpp

This adds support of XEP-0359: Unique and Stable Stanza IDs in version
0.6.0.

Implement XEP-0359: Unique and Stable Stanza IDs

---

README.md

It's banned and I can't find any messages/topics in it.
@jlaine, @tehnick or @0xd34df00d can you confirm?

README: Remove google group

---

src/base/QXmppDataForm.cpp
src/base/QXmppDataForm.h
tests/qxmppregisteriq/tst_qxmppregisteriq.cpp

This makes creating forms manually a lot easier.

QXmppDataForm: Add ctor with all attributes

---

src/CMakeLists.txt
src/client/QXmppCallStream.h

Avoid depending on GStreamer in public headers

---

src/base/QXmppGlobal.h.in
src/base/QXmppUtils.cpp
tests/qxmppbitsofbinarycontentid/tst_qxmppbitsofbinarycontentid.cpp
tests/qxmppmessage/tst_qxmppmessage.cpp
tests/qxmppstreaminitiationiq/tst_qxmppstreaminitiationiq.cpp

We only test 5.9 with the CI... :/

Fix build with Qt 5.7

---

src/base/QXmppDataForm.cpp
src/base/QXmppDataForm.h
tests/qxmppdataform/tst_qxmppdataform.cpp

(I need this on my pubsub branch.)

QXmppDataForm: Add FORM_TYPE search function

---

src/CMakeLists.txt
src/base/QXmppGlobal.h.in
src/base/QXmppGlobal_p.h
src/base/QXmppPacket.cpp
src/base/QXmppPacket_p.h
src/base/QXmppStream.cpp
src/base/QXmppStream.h
src/base/QXmppStreamManagement.cpp
src/base/QXmppStreamManagement_p.h
src/client/QXmppClient.cpp
src/client/QXmppClient.h
src/client/QXmppDiscoveryManager.cpp
src/client/QXmppDiscoveryManager.h
src/client/QXmppEntityTimeManager.cpp
src/client/QXmppEntityTimeManager.h
src/client/QXmppOutgoingClient.cpp
src/client/QXmppUploadRequestManager.cpp
src/client/QXmppUploadRequestManager.h

Add QFuture support

---

src/client/QXmppClient.cpp
src/client/QXmppClient.h
tests/TestClient.h

Before opening a pull-request please check you've done:

QXmppClient: Add addNewExtension<T>()

---

src/base/QXmppFutureUtils_p.h
src/base/QXmppStream.cpp

QXmppStream: Refactor and simplify IQ handling

---

src/base/QXmppPubSubNodeConfig.cpp
src/base/QXmppPubSubNodeConfig.h

PubSubNodeConfig: Add Max option to maxItems

---

doc/xep.doc
src/CMakeLists.txt
src/base/QXmppGlobal.h.in
src/base/QXmppMessage.cpp
src/base/QXmppMessage.h
src/base/QXmppPacket.cpp
src/base/QXmppPacket_p.h
src/base/QXmppPubSubEvent.cpp
src/base/QXmppPubSubEvent.h
src/base/QXmppStanza.cpp
src/base/QXmppStanza.h
src/base/QXmppStream.cpp
src/base/QXmppStream.h
src/client/QXmppAtmManager.cpp
src/client/QXmppClient.cpp
src/client/QXmppClient.h
src/client/QXmppClient_p.h
src/client/QXmppDiscoveryManager.cpp
src/client/QXmppE2eeExtension.cpp
src/client/QXmppE2eeExtension.h
src/client/QXmppEntityTimeManager.cpp
src/client/QXmppPubSubManager.cpp
src/client/QXmppRosterManager.cpp
src/client/QXmppUploadRequestManager.cpp
tests/qxmppclient/tst_qxmppclient.cpp
tests/qxmppmessage/tst_qxmppmessage.cpp

Implement Stanza Content Encryption

---

src/client/QXmppAtmManager.cpp

Fix compilation with Qt6

---

doc/xep.doc
src/base/QXmppConstants.cpp
src/base/QXmppConstants_p.h
src/base/QXmppMessage.cpp
src/base/QXmppMessage.h

Update to XEP-0380 version 0.4

---

src/base/QXmppFutureUtils_p.h
src/client/QXmppClient.cpp

Several encryption / sending improvements

---

src/client/QXmppAtmManager.cpp
src/client/QXmppTrustMemoryStorage.cpp
src/client/QXmppTrustMemoryStorage.h
src/client/QXmppTrustStorage.cpp
src/client/QXmppTrustStorage.h
tests/qxmppatmmanager/tst_qxmppatmmanager.cpp
tests/qxmpptrustmemorystorage/tst_qxmpptrustmemorystorage.cpp

Refactor trust storage

---

src/base/QXmppStanza.cpp
src/base/QXmppStanza.h
tests/qxmppstanza/tst_qxmppstanza.cpp

Stanza::Error: Add optional overloads for Condition/Type

---

src/base/QXmppMessage.cpp
src/base/QXmppMessage.h
tests/qxmppmessage/tst_qxmppmessage.cpp

Message: Add end-to-end encryption fallback body

---

doc/xep.doc

doc: xep: Add XEP-0333: Chat Markers

---

src/base/QXmppStanza.h

Stanza: Remove unused include

---

src/CMakeLists.txt
src/base/QXmppGlobal.cpp
src/base/QXmppGlobal.h
src/base/QXmppGlobal_p.h
src/base/QXmppMessage.cpp
src/base/QXmppMessage.h
src/base/QXmppStanza.cpp
src/base/QXmppStanza.h
tests/qxmppmessage/tst_qxmppmessage.cpp
tests/qxmppstanza/tst_qxmppstanza.cpp

Add used encryption

---

README.md

README: Document 'BUILD_INTERNAL_TESTS'

---

tests/qxmppomemodata/tst_qxmppomemodata.cpp

tests: OmemoData: Add test for OmemoIq

---

doc/xep.doc
src/base/QXmppConstants.cpp
src/base/QXmppConstants_p.h
src/client/QXmppPubSubManager.cpp
src/client/QXmppPubSubManager.h
tests/qxmpppubsubmanager/tst_qxmpppubsubmanager.cpp

PubSub / PEP improvements

---

src/base/QXmppMessage.cpp
src/base/QXmppMessage.h

Message: Apply clang-format

---

src/CMakeLists.txt
src/client/QXmppClient.cpp
src/client/QXmppClient.h
src/client/QXmppE2eeExtension.h
src/client/QXmppSendStanzaParams.cpp
src/client/QXmppSendStanzaParams.h
tests/qxmppclient/tst_qxmppclient.cpp

Add SendStanzaParams class

---

src/client/QXmppCallStream.cpp
src/client/QXmppClient.cpp
src/client/QXmppClientExtension.h
src/client/QXmppPubSubEventHandler.h
tests/util.h

Apply 'clang-format'

---

README.md

README: Add badge for support chat

---

.github/workflows/tests.yml

Add REUSE compliance check action

---

.github/workflows/push-docs.yml
.github/workflows/tests.yml

ci: Update install-qt-action to v3

---

src/base/QXmppHash.cpp
src/base/QXmppHash.h

QXmppHash: Add getters and setters

---

doc/doap.xml

doc: doap: Update XEP-0308 version

---

doc/doap.xml

doc: doap: Fix XEP-0333: Chat Markers support

---

src/CMakeLists.txt
src/base/QXmppError.cpp
src/base/QXmppError.h
src/base/QXmppHashing.cpp
src/base/QXmppHashing_p.h
tests/qxmpputils/tst_qxmpputils.cpp
tests/util.h

- QXmppError: Add fromIoDevice()
- Add multithreaded hashing functions
PR check list:

Add multithreaded hashing functions

---

src/base/QXmppEncryptedFileSource.cpp
src/base/QXmppEncryptedFileSource.h
tests/qxmppmessage/tst_qxmppmessage.cpp

Make encrypted file source public

---

CMakeLists.txt
src/CMakeLists.txt
src/base/QXmppEncryptedFileSource.cpp
src/base/QXmppEncryptedFileSource.h
src/base/QXmppFileShare.cpp
src/base/QXmppFileShare.h
src/base/QXmppGlobal.h
src/client/QXmppFileEncryption.cpp
src/client/QXmppFileEncryption.h
src/client/QcaInitializer.cpp
src/client/QcaInitializer_p.h
src/omemo/QXmppOmemoManager_p.h
tests/CMakeLists.txt
tests/qxmppfileencryption/tst_qxmppfileencryption.cpp
tests/qxmppmessage/tst_qxmppmessage.cpp

Add file encryption functions and Encryption/DecryptionDevice

---

doc/doap.xml
src/base/QXmppConstants.cpp
src/base/QXmppConstants_p.h
src/base/QXmppJingleIq.cpp
src/base/QXmppJingleIq.h
src/base/QXmppPresence.cpp
src/base/QXmppPresence.h
tests/qxmppjingleiq/tst_qxmppjingleiq.cpp
tests/qxmpppresence/tst_qxmpppresence.cpp

Implement XEP-0272: Multiparty Jingle (Muji) stanza parts

---

doc/doap.xml
src/base/QXmppJingleIq.cpp
src/base/QXmppJingleIq.h
tests/qxmppjingleiq/tst_qxmppjingleiq.cpp

Implement XEP-0167: Jingle RTP Sessions multiplexing

---

doc/doap.xml

doap: Add missing end tag

---

src/CMakeLists.txt
src/base/QXmppMessage.cpp
src/base/QXmppMessage.h
src/base/QXmppOutOfBandUrl.cpp
src/base/QXmppOutOfBandUrl.h
tests/qxmppmessage/tst_qxmppmessage.cpp

Allow adding multiple oob urls and a description

---

doc/doap.xml
src/base/QXmppConstants.cpp
src/base/QXmppConstants_p.h
src/base/QXmppJingleIq.cpp
src/base/QXmppJingleIq.h
tests/qxmppjingleiq/tst_qxmppjingleiq.cpp

Implement XEP-0293: Jingle RTP Feedback Negotiation stanza parts

---

src/base/QXmppJingleIq.cpp

JingleIq::Content: Specify implemented XEP in documentation of 'descriptionSsrc'

---

doc/doap.xml
src/CMakeLists.txt
src/base/QXmppFileShare.cpp
src/base/QXmppFileShare.h
src/base/QXmppUtils.cpp
src/base/QXmppUtils_p.h
src/client/QXmppDownload.cpp
src/client/QXmppDownload.h
src/client/QXmppEncryptedHttpFileSharingProvider.cpp
src/client/QXmppEncryptedHttpFileSharingProvider.h
src/client/QXmppFileSharingManager.cpp
src/client/QXmppFileSharingManager.h
src/client/QXmppFileSharingProvider.h
src/client/QXmppFileTransfer.cpp
src/client/QXmppFileTransfer.h
src/client/QXmppHttpFileSharingProvider.cpp
src/client/QXmppHttpFileSharingProvider.h
src/client/QXmppHttpUploadManager.cpp
src/client/QXmppUpload.cpp
src/client/QXmppUpload.h

Implement Stateless File Sharing

---

tests/qxmppjingleiq/tst_qxmppjingleiq.cpp

tests: JingleIq: Improve testing RTP Feedback Negotiation

---

doc/doap.xml
src/base/QXmppJingleIq.cpp
src/base/QXmppJingleIq.h
src/client/QXmppCallManager.cpp
tests/qxmppjingleiq/tst_qxmppjingleiq.cpp

Implement XEP-0167: Jingle RTP Sessions Informational Messages

---

doc/doap.xml

doc: doap: Add RFCs and sort elements consistently

---

doc/doap.xml
src/base/QXmppConstants.cpp
src/base/QXmppConstants_p.h
src/base/QXmppJingleIq.cpp
src/base/QXmppJingleIq.h
tests/qxmppjingleiq/tst_qxmppjingleiq.cpp

Implement XEP-0294: Jingle RTP Header Extensions Negotiation stanzas

---

doc/doap.xml
src/base/QXmppJingleIq.cpp
src/base/QXmppJingleIq.h
tests/qxmppjingleiq/tst_qxmppjingleiq.cpp

Implement XEP-0167: Jingle RTP Sessions SRTP negotiation

---

.github/workflows/tests.yml

.github: workflows: Test XML syntax

---

tests/qxmppjingleiq/tst_qxmppjingleiq.cpp

PR check list:
This fixes errors while comparing 'uint32_t' values introduced by commit b020af2439342e3f748ecdcad6d4db4d5a8a2880.

tests: JingleIq: Test RTP crypto element separately and fix comparisons

---

src/omemo/QXmppOmemoManager_p.cpp

OmemoManagerPrivate: Capture lambda expression parameters explicitly

---

src/CMakeLists.txt
src/base/QXmppDiscoveryIq.cpp
src/base/QXmppDiscoveryIq.h
src/base/QXmppEntityTimeIq.cpp
src/base/QXmppEntityTimeIq.h
src/base/QXmppVCardIq.cpp
src/base/QXmppVCardIq.h
src/base/QXmppVersionIq.cpp
src/base/QXmppVersionIq.h
src/client/QXmppDiscoveryManager.cpp
src/client/QXmppDiscoveryManager.h
src/client/QXmppEntityTimeManager.cpp
src/client/QXmppEntityTimeManager.h
src/client/QXmppIqHandling.cpp
src/client/QXmppIqHandling.h
src/client/QXmppVersionManager.cpp
src/client/QXmppVersionManager.h

- Add automated IQ request handling functions
- Add checkIqType() function to IQs
- DiscoveryManager: Use new IQ request handling
- VersionManager: Use new IQ request handling
PR check list:

New IQ request handling

---

src/omemo/QXmppOmemoManager_p.cpp

OmemoManagerPrivate: Fix error messages

---

doc/index.doc
src/omemo/QXmppOmemoManager.cpp

* OmemoManager: Use new CarbonManagerV2 and addNewExtension() for class documentation
* OmemoManager: Remove unneeded Doxygen references for method documentation
* doc: index: Add OmemoManager
PR check list:

Improve and update OMEMO documentation

---

src/omemo/QXmppOmemoManager_p.cpp
src/omemo/QXmppOmemoManager_p.h

OmemoManagerPrivate: Fix device setup

---

doc/doap.xml

doap: Add releases 1.5.0 and 1.5.1

---

doc/doap.xml

doap: Mark XEP-0167: Jingle RTP Sessions as complete

---

.github/workflows/tests.yml

.github: workflows: Add C++ linter

---

README.md

README: Add Doxygen as dependency

---

src/base/QXmppPromise.h
src/client/QXmppDiscoveryManager.h
src/client/QXmppEntityTimeManager.h
src/client/QXmppFileEncryption.cpp
src/client/QXmppFileEncryption.h

Fix compilation on MSVC 2019

---

src/base/QXmppExternalServiceDiscoveryIq.h
src/omemo/QXmppOmemoData.cpp
src/omemo/QXmppOmemoManager.cpp
src/omemo/QXmppOmemoManager_p.cpp
src/omemo/QXmppOmemoManager_p.h

omemo: Fix build on MSVC 2019

---

src/omemo/QXmppOmemoManager.cpp

PR check list:
The changes are insignificant, it doesn't feel like it requires to document them or do some meta work.
But if you'll tell - I'm gonna try to cover that case in unit testing

added some probably forgotten promise resolutions

---

src/omemo/QXmppOmemoManager.cpp

OmemoManager: Remove unneeded '/'

---

src/client/QXmppBlockingManager.cpp
tests/qxmppblockingmanager/tst_qxmppblockingmanager.cpp

This way, the manager will never send more than one fetch request per
stream.
PR check list:

BlockingManager: Only send one IQ request on multiple fetch() calls

---

tests/qxmppomemomanager/tst_qxmppomemomanager.cpp

- **tests: omemomanager: Fix small warnings**
- **tests: omemomanager: Fix usage of unexported symbols**

tests: omemomanager: Fix usage of unexported symbols

---

src/omemo/QXmppOmemoManager_p.cpp

OmemoManager: Fix decryption of group chat messages

---

src/client/QXmppMixManager.cpp
tests/qxmppmixmanager/tst_qxmppmixmanager.cpp

MixManager: Various fixes/improvements

---

src/client/QXmppMessageReceiptManager.cpp

MessageReceiptManager: Advise server to always store receipts

---

doc/doap.xml
src/base/QXmppFileShare.cpp
src/base/QXmppFileShare.h
src/base/QXmppMessage.cpp
src/base/QXmppMessage.h
tests/qxmppmessage/tst_qxmppmessage.cpp

It has been added in v0.3 of the XEP.
PR check list:

Update SFS to v0.3

---

src/CMakeLists.txt
src/base/QXmppConstants_p.h
src/base/QXmppRosterIq.cpp
src/base/QXmppRosterIq.h
src/base/QXmppTask.cpp
src/base/QXmppTask.h
src/base/QXmppVCardIq.cpp
src/base/QXmppVCardIq.h
src/client/QXmppAccountMigrationManager.cpp
src/client/QXmppAccountMigrationManager.h
src/client/QXmppClient.cpp
src/client/QXmppClient.h
src/client/QXmppClientExtension.cpp
src/client/QXmppClientExtension.h
src/client/QXmppRosterManager.cpp
src/client/QXmppRosterManager.h
src/client/QXmppVCardManager.cpp
src/client/QXmppVCardManager.h
tests/CMakeLists.txt
tests/TestClient.h
tests/qxmppaccountmigrationmanager/tst_qxmppaccountmigrationmanager.cpp
tests/qxmppvcardmanager/tst_qxmppvcardmanager.cpp
tests/util.h

This PR replaces #584.
PR check list:
Funded by [NLnet](https://nlnet.nl/foundation/) via [NGI Zero Entrust](https://nlnet.nl/entrust/).

Client manager for exporting/importing of account data

---

src/omemo/QXmppOmemoManager.cpp

OmemoManager: Document return values

---

src/client/QXmppMixManager.cpp
src/client/QXmppMixManager.h
tests/qxmppmixmanager/tst_qxmppmixmanager.cpp

PR check list:
Is part of #624

MixManager: Rename server features and add enum for unknown support case

---

src/client/QXmppRosterManager.cpp
tests/qxmppaccountmigrationmanager/tst_qxmppaccountmigrationmanager.cpp

We can only request adding roster items one by one
PR check list:

Fix QXmppAccountMigrationManager issues

---

src/client/QXmppMixManager.cpp

MixManager: Improve and extend documentation

---

doc/doap.xml
src/base/QXmppConstants_p.h
src/base/QXmppMessage.cpp
src/base/QXmppMessage.h
tests/qxmppmessage/tst_qxmppmessage.cpp

PR check list:
**Funded by [NLnet](https://nlnet.nl/foundation/) via [NGI Assure](https://nlnet.nl/assure/).**

Implement XEP-0461: Message Replies: parsing of message extension

---

src/omemo/QXmppOmemoManager_p.cpp

OmemoManager: Move errors when passing them

---

doc/doap.xml

Update DOAP file

---

.github/workflows/tests.yml
src/omemo/QXmppOmemoManager_p.cpp

Build QXmpp with OMEMO on the CI on windows

ci: windows: Build with OMEMO enabled

---

src/client/QXmppMixManager.cpp
tests/qxmppmixmanager/tst_qxmppmixmanager.cpp

MixManager: Fix discovery items/info retrieval

---

src/client/QXmppMamManager.cpp

MamManager: Fix method documentation

---

doc/doap.xml

doap: Add XEP-0453: DOAP usage in XMPP

---

src/base/QXmppStun.h

Stun: Include QSet to fix incomplete type
