src/server/QXmppServer.cpp, src/server/QXmppServer.h
I've added the possibility to set the local TLS certificate and private key as QSslCertificate and QSslKey objects.
This makes it possible to use encryped private keys, DER encoded certificates and detect problems with the certificate.
=> Set local TLS certificate and private key as QSslCertificate and QSslKey

src/client/QXmppTransferManager.cpp, tests/qxmpptransfermanager/tst_qxmpptransfermanager.cpp
As it is already done in the QXmppTransferJob::accept method, QXmppTransferManager::sendFile should also convert the local file path to a QUrl using the QUrl::fromLocalFile method.
=> File transfer: Make sure the filename is being converted to a QUrl correctly

src/client/QXmppTransferManager.cpp
Prevent device reparenting and close the dev only if we opened it.
sendFile() method expects the device to be opened, but
QXmppTransferJob::terminate() closes the dev unconditionaly, which
breaks reusable QIODevice workflow.
E.g. current code closes an input-output buffer after transfer,
before the data from buffer read.
Device parent setup also cause the device deletion, which is not
expected in some cases.
This issue affects https://github.com/TelepathyQt/telepathy-nonsense project, which uses the same device to read/write file content from/to xmpp and to write/read the content to/from TelepathyQt FileTransfer interface.
I understand that this can lead to memory-leak, if a device, passed to QXmpp is allocated on heap, have no parent and not deleted manually, but I'm sure that this is …
=> QXmppTransferManager: Fixed device management

qxmpp.prf
.prf file provided as requested in https://github.com/qxmpp-project/qxmpp/issues/100
It's a rough adaptation of the feature file provided by the QtOAuth library. There are things I don't really understand, and conditionals for platforms I don't use, but it can be used as a starting point.
It will certainly make life easier (and safer) for people creating qmake-based projects which link to QXMPP, especially considering how some distributions might provide both Qt4 and Qt5 builds of QXMPP with different sonames and such.
I've tested it on my system, by copying the new file to /usr/lib/qt{4|5}/mkspecs/features/ and using "CONFIG += qxmpp" on my .pro file, and it works as expected.
Cheers!
=> Added a qmake CONFIG feature file

src/base/QXmppStream.cpp
This is important for reconnects.
It fixes the latest discussion in https://github.com/qxmpp-project/qxmpp/issues/66
=> Set Stream Management to disabled when the socket becomes ready

CMakeLists.txt, QXmppConfig.cmake, QXmppConfig.cmake.in
Now we also generate a QXmppConfigVersion.cmake file.
This allows other applications to depend on a specific (or minimum) version of QXmpp.
=> CMake: Use CMakePackageConfigHelpers to generate the package config

tests/travis/build-and-test, tests/travis/install-build-depends
With this change we will use the CMake version provided by Ubuntu Xenial and not the updated one from Travis.
=> travis: Only use system binaries

tests/CMakeLists.txt, tests/qxmpptransfermanager/CMakeLists.txt, tests/qxmpputils/CMakeLists.txt
This PR contains three small fixes for the CMake build system.
=> CMake: Add binary paths for tests to the include paths

src/base/QXmppConstants.cpp, src/base/QXmppConstants_p.h, src/base/QXmppMessage.cpp, src/base/QXmppMessage.h, tests/qxmppmessage/tst_qxmppmessage.cpp
Today this is most important for attaching URLs generated by XEP-0363:
HTTP File Upload for a very basic form of media/file sharing.
The defined IQ protocol has not been implemented.
=> Add partial support of XEP-0066: Out of Band Data

src/client/QXmppDiscoveryManager.cpp, src/client/QXmppVersionManager.cpp
The QXmppVersionManager will use QSysInfo in Qt 5.4 or later to
determine the client's OS, so it will also contain the OS version or
some codenames.
=> Use QSysInfo for client OS in VersionManager

src/base/QXmppSasl.cpp, src/client/QXmppConfiguration.cpp, src/client/QXmppOutgoingClient.cpp, tests/qxmppsasl/tst_qxmppsasl.cpp
The previous logic was:
- use the preferred SASL mechanism if available
- otherwise use the first supported mechanism offered by the server
However RFC 6120, section 6.3.3 states:
"The initiating entity MUST maintain its own preference order independent
of the preference order of the receiving entity."
The new logic is:
- order our supported mechanisms from most secure to least secure
- if the user sets QXmppConfiguration::saslMechanism, put it first
- use the best mechanism supported by the server
=> [sasl] order mechanisms to prefer the most secure

CMakeLists.txt
This is required to make cmake correctly detect compiler features in a macOS cross compiling environment (https://git.kaidan.im/kaidan/dockerfiles/blob/master/mac-osxcross/Dockerfile) and probably also for some clang setups on a native macOS machine.
=> cmake: Set minimum version first and increase it to 3.3

src/base/QXmppDiscoveryIq.cpp, src/base/QXmppJingleIq.cpp, src/base/QXmppStun.cpp, src/client/QXmppOutgoingClient.cpp
This fixes multiple warnings when compiling with Qt 5.13 and will simplify the transition to Qt 6 once it's released.
The next thing to do (in a new PR) is porting away from the deprecated foreach (also known as Q_FOREACH) macro which is unfortunately used 155 times...
=> Port away from deprecated qt features

CHANGELOG.md, doc/xep.doc, src/base/QXmppConstants.cpp, src/base/QXmppConstants_p.h, src/base/QXmppMessage.cpp, src/base/QXmppMessage.h, tests/qxmppmessage/tst_qxmppmessage.cpp
This adds parsing and serialization for XEP-0367: Message Attaching in
version 0.3.0.
=> Implement XEP-0367: Message Attaching

src/base/QXmppConstants.cpp, src/base/QXmppConstants_p.h, src/base/QXmppStreamFeatures.cpp, src/base/QXmppStreamFeatures.h, tests/qxmppstreamfeatures/tst_qxmppstreamfeatures.cpp
This adds parsing, serialization and a test for the 'register' stream
feature of XEP-0077: In-Band Registration.
Co-authored-by: Linus Jahn <lnj@kaidan.im>
---
This will be required for actually registering with a server (PRs for that will follow).
=> Add register stream feature

CHANGELOG.md, doc/xep.doc, src/base/QXmppConstants.cpp, src/base/QXmppConstants_p.h, src/base/QXmppMessage.cpp, src/base/QXmppMessage.h, tests/qxmppmessage/tst_qxmppmessage.cpp
This adds parsing and serialization for XEP-0380: Explicit Message
Encryption in version 0.2.0.
=> Implement XEP-0380: Explicit Message Encryption

CHANGELOG.md, doc/xep.doc, src/base/QXmppConstants.cpp, src/base/QXmppConstants_p.h, src/base/QXmppMessage.cpp, src/base/QXmppMessage.h, tests/qxmppmessage/tst_qxmppmessage.cpp
REPLACES #10!
This implements parsing and serialization of XEP-0334: Message
Processing Hints in version 0.3.0.
https://xmpp.org/extensions/xep-0334.html
Co-authored-by: Juan Aragon <jaaragont@gmail.com>
Co-authored-by: Sam Truscott <sam@wumpus.co.uk>
=> Implement XEP-0334: Message Processing Hints

src/client/QXmppOutgoingClient.cpp
`socketError()` calls `connectToNextDNSHost()` which might cause `socketError()` synchronously (and recursively), thus not giving a change for updating `nextSrvRecordIdx`.
Overall, this results in attempting to connect to the same DNS record recursively, until the stack is exhausted, resulting in SEGFAULT.
One of the solutions (done in this commit) is to increment the record index _before_ attempting to connect.
Despite "potential" in the name, it turns out to be a real issue one of the users of my software has faced, resulting in ~76000 frames of
```
#76768 0x00007fb51e57cdea in QAbstractSocket::connectToHost(QString const&, unsigned short, QFlags<QIODevice::OpenModeFlag>, QAbstractSocket::NetworkLayerProtocol) () at /usr/lib/x86_64-linux-gnu/libQt5Network.so.5
#76769 0x00007fb51e5ae8b5 …
```
=> Fix potential SEGFAULT on connection error

src/base/QXmppConstants.cpp, src/base/QXmppConstants_p.h, src/base/QXmppMessage.cpp, src/base/QXmppMessage.h, tests/qxmppmessage/tst_qxmppmessage.cpp
This simplifies parsing and fixes a possible bug:
The bug case looks like this:
- We have one element we want to parse (e,g, "attachment" with namespace xyz)
- There is another element called "attachment" in the stanza and it's
located before the other element.
- QXmppMessage tries to parse the attachment element using
firstChildElement("attachment") and checks the namespace
- The namespace (of the first) element doesn't match
- The actual "attachment" element is not parsed
This also fixes the "constructor does not initialize these fields: […]"
warnings for QXmppMessagePrivate.
=> Refactor & clean up QXmppMessage

src/base/QXmppRosterIq.cpp, src/base/QXmppRosterIq.h, tests/qxmpprosteriq/tst_qxmpprosteriq.cpp
This reverts commit 740a085ef7ac707e2cc2217edf02e296c3f7692e.
There were talks on the standards mailing list that the XEP will be
changed and a private PEP node is used for distributing joined channels.
Also no server (that I am aware of) supports the MIX roster extension,
so I think it is the best we remove before the next release, so we do
not have problems with deprecations and ABI compatibility.
=> Revert "Implement MIX-PAM XEP-0405: Roster IQ extension"

src/base/QXmppIq.h, src/base/QXmppLogger.h, src/base/QXmppRtpChannel.h, src/base/QXmppStun.h, src/client/QXmppCallManager.h, src/client/QXmppClient.h, src/client/QXmppTransferManager.h, tests/qxmppcallmanager/tst_qxmppcallmanager.cpp, tests/qxmpptransfermanager/tst_qxmpptransfermanager.cpp
Q_ENUM exists since Qt 5.5, more details can be found here:
https://woboq.com/blog/q_enum.html
=> Replace deprecated Q_ENUMS with Q_ENUM

AUTHORS, src/base/QXmppHttpUploadIq.cpp, src/base/QXmppHttpUploadIq.h, src/base/QXmppMixIq.cpp, src/base/QXmppMixIq.h, src/base/QXmppMixItem.cpp, src/base/QXmppMixItem.h, src/base/QXmppResultSet.cpp, src/base/QXmppResultSet.h, src/client/QXmppUploadRequestManager.cpp, src/client/QXmppUploadRequestManager.h
Mostly this was a mistake by me in earlier contributions.
=> Replace emails in copyright headers by entries in the AUTHORS file

src/base/QXmppGlobal.h.in
QT_VERSION_CHECK() returns the same format as is currently used, it is
easier to read and fixes a problem that could occur with the previous
marco. The macro was unenclosed causing comparison to fail. This also
happened in Kaidan [1].
[1]: https://invent.kde.org/kde/kaidan/commit/5a3e5e8a748488f4d55302b4beacce880dde381a
=> QXmppGlobal: Use QT_VERSION_CHECK() to generate QXMPP_VERSION

src/client/QXmppClient.h, tests/qxmppclient/tst_qxmppclient.cpp
This is useful when you need to insert an extension after another or before.
=> QXmppClient: Add method to get index of extension

src/base/QXmppRegisterIq.cpp, src/base/QXmppRegisterIq.h, tests/qxmppregisteriq/tst_qxmppregisteriq.cpp
This adds utility methods to create an unregistration or a change
password request in one line.
=> QXmppRegisterIq: Add utility methods to create common requests

src/base/QXmppRegisterIq.cpp, src/base/QXmppRegisterIq.h, tests/qxmppregisteriq/tst_qxmppregisteriq.cpp, tests/qxmppregistrationmanager/tst_qxmppregistrationmanager.cpp
This can be done without any concerns, because the registerType was not
part of any release yet.
=> Refactor QXmppRegisterIq: Replace registerType by two separate attr.

doc/xep.doc, src/base/QXmppConstants.cpp, src/base/QXmppConstants_p.h, src/base/QXmppMessage.cpp, src/base/QXmppMessage.h, tests/qxmppmessage/tst_qxmppmessage.cpp
This adds support of XEP-0428: Fallback Indication in version 0.1.0.
https://xmpp.org/extensions/xep-0428.html
=> Implement XEP-0428: Fallback Indication

src/base/QXmppUtils.cpp, src/base/QXmppUtils.h, tests/qxmpputils/tst_qxmpputils.cpp
The QXmppUtils::generateStanzaHash() generates UUIDs by default now.
UUIDs are not generated, if the default parameter is changed to a
different value (!= 36). The behaviour is not changed for other values
than 36.
This way all users of QXmpp will automatically start to use UUIDs, if
they use the generateStanzaHash() method.
=> utils: Generate UUIDs for stanza hashes by default

doc/xep.doc, src/base/QXmppConstants.cpp, tests/qxmppmammanager/tst_qxmppmammanager.cpp
This updates the MAM implementation to version 0.6.0. The new namespace
is now used (mam:2). There is no compatibility layer with the old
namespace (mam:1) since both ejabberd and prosody have updated their MAM
implementation to support the mam:2 namespace a while ago.
Closes #254.
=> Update MAM implementation to v0.6

src/client/QXmppOutgoingClient.cpp
Support `not-authorized` condition for `stream:error`.
This allow us to distinguish `stream:error` conditions more specifically.
Please refer to https://xmpp.org/rfcs/rfc6120.html#streams-error-conditions-not-authorized.
=> Add not authorized condition for stream error

doc/xep.doc, src/base/QXmppMessage.cpp, src/base/QXmppMessage.h, tests/qxmppmessage/tst_qxmppmessage.cpp
This adds parsing for recognizing /me commands in message bodies. It
complies with version 1.0 of XEP-0245: The /me Command.
https://xmpp.org/extensions/xep-0245.html
=> Implement XEP-0245: The /me Command

src/base/QXmppStanza.h
The <payment-required/> error condition was not adopted in RFC6120 as it
was unused.
=> Deprecate PaymentRequired error condition

src/client/QXmppRosterManager.cpp
The *ask* attribute must not be included. See https://tools.ietf.org/html/rfc6121#section-2.1.2.2.
=> Do not include 'ask' attribute when renaming roster item

src/client/QXmppCallStream.cpp, src/client/QXmppCallStream.h, src/client/QXmppCallStream_p.h
Allows to use non-static functions (or lambdas with captures)
This should even to some extend be source compatible.
=> QXmppCallStream: Wrap callback in std::function

src/base/QXmppMessage.cpp, src/base/QXmppMessage.h, tests/qxmppmessage/tst_qxmppmessage.cpp
The 'parent' attribute for <thread/> element in messages has been
introduced in RFC6121. This commit adds parsing and serialization for
it, including unit tests.
=> QXmppMessage: Add parent thread attribute from RFC6121

src/base/QXmppRosterIq.cpp
If the IQ stanza does not contain a subscription state (that is the case when the stanza contains a subscription status (`ask` attribute)), it should be set correctly as `NotSet` because otherwise the warning `QXmppRosterIq::Item::setTypeFromStr(): invalid type` is logged.
=> Set QXmppRosterIq subscription type correctly

src/CMakeLists.txt, src/base/QXmppGlobal.h.in
Following the discussion on issue #297, here's my attempt to solve it.
=> Fixing QXmppGlobal.h for static linking

src/client/QXmppMessageReceiptManager.cpp, tests/qxmppmessagereceiptmanager/tst_qxmppmessagereceiptmanager.cpp
Not only receipt requests, but also receipts from error messages should
not be used.
=> QXmppMessageReceiptManager: Ignore *all* error messages

src/client/QXmppCarbonManager.cpp, src/client/QXmppCarbonManager.h, tests/qxmppcarbonmanager/tst_qxmppcarbonmanager.cpp
The XEP requires that only carbon messages from the client's bare JID
are accepted. This prevents that other entities can inject messages into
the client.
=> QXmppCarbonManager: Fix vulnerability: Add sender check

CMakeLists.txt, examples/example_7_archiveHandling/example_7_archiveHandling.cpp, src/CMakeLists.txt, src/base/QXmppBookmarkSet.cpp, src/base/QXmppRpcIq.cpp, src/base/QXmppSasl.cpp, tests/qxmppregistrationmanager/tst_qxmppregistrationmanager.cpp
I have those always enabled, which is how I detected these issues.
This avoids QUrl/QString confusions, and QString/QByteArray confusions.
=> Enable QURL_NO_CAST_FROM_STRING+QT_NO_CAST_TO_ASCII and fix compilation

src/client/QXmppTransferManager.cpp
`featureForm()` returns a `QXmppDataForm` by value - directly taking a reference to a member of this class is undefined behavior and leads to a crash.
This PR changes the code to take references to both the form and the fields inside, thus extending the lifetime to the end of the function, fixing said crash.
=> Fix UB in QXmppTransferManager when parsing stream features

src/server/QXmppOutgoingServer.cpp
The attributes are mandatory (see RFC 6120 paragraphs [8.1.1.2](https://tools.ietf.org/html/rfc6120#section-8.1.1.2) and [8.1.2.2](https://tools.ietf.org/html/rfc6120#section-8.1.2.2); also the attributes are listed in the example of stream header for [XEP-0220](https://xmpp.org/extensions/xep-0220.html#advertisement-traditional)).
This commit fixes S2S messaging with Prosody server (and probably many others).
=> server: Add 'to' and 'from' attributes to dialback init stream header

src/base/QXmppStream.cpp, src/base/QXmppStream.h, src/base/QXmppStreamManagement.cpp, src/base/QXmppStreamManagement_p.h, src/client/QXmppClient.cpp, src/client/QXmppClient.h, src/client/QXmppOutgoingClient.cpp, src/client/QXmppOutgoingClient.h, src/client/QXmppRosterManager.cpp, src/client/QXmppRosterManager.h
* Separating the stream management stuff will make the implementation of the QFuture stuff easier (see #96).
* having the stream management state accessible from the QXmppClient will make it possible to fix some  TODOs (The roster manager should not re-request the roster when the stream is resumed, the QXmppClient should not resend presence)
I'm interested in your feedback.
=> Refactor stream management

tests/IntegrationTesting.h, tests/qxmppvcardmanager/tst_qxmppvcardmanager.cpp
In some cases it's hard to test managers or the client itself because it would require a server implementation and a real connection. Implementing everything in QXmpp server would be nice, but is time consuming and in many cases not really needed by anyone. The simpler solution is to test QXmpp with an external server (like a real world ejabberd or prosody server). This also has the advantage that we can test whether QXmpp properly works with other server implementations and if there are any compliance issues (in QXmpp or in a server implementation).
These are the reasons I started to work on simple integration tests. The current approach is using environment variables for the XMPP account JID + password to be used. The integration tests are integrated into the other unit tests, but are …
=> Add integration tests

src/base/QXmppStream.cpp, src/base/QXmppStream.h, src/base/QXmppStreamManagement.cpp, src/base/QXmppStreamManagement_p.h, src/client/QXmppClient.cpp
The stream management mechanisms cache sent packages until the client
receives an acknowledgement from the server. When the connection gets
lost, the client resends all packages from the last connection that
have not been acknowledged.
And here comes the problem: When connecting with a different JID, the
client still resends all packages from the last connection. Packages
that were never intended to be sent from another account / to another
server.
This commit fixes this behaviour by resetting the package cache, when
the JID changes.
=> QXmppClient: Reset Stream Management package cache on JID changes

src/base/QXmppFutureUtils_p.h, src/base/QXmppGlobal.h.in, src/client/QXmppClient.cpp, src/client/QXmppClient.h, src/client/QXmppDiscoveryManager.cpp, src/client/QXmppEntityTimeManager.cpp, src/client/QXmppRosterManager.cpp, src/client/QXmppRosterManager.h, src/client/QXmppUploadRequestManager.cpp
Before opening a pull-request please check you've done:
=> RosterManager: Add QFuture-based requests

src/base/QXmppDataForm.cpp, src/client/QXmppCallManager.cpp, src/client/QXmppTransferManager.cpp
=> Use qMakePair() again to fix compile errors

.clang-format
This change is made to comply with https://github.com/qxmpp-project/qxmpp/pull/353#discussion_r696720652 and https://github.com/qxmpp-project/qxmpp/pull/353#discussion_r696720778.
=> clang-format: Use brace wrapping after struct

src/CMakeLists.txt, src/client/QXmppAtmManager.cpp, src/client/QXmppAtmManager.h, src/client/QXmppAtmTrustMemoryStorage.cpp, src/client/QXmppAtmTrustMemoryStorage.h, src/client/QXmppAtmTrustStorage.cpp, src/client/QXmppAtmTrustStorage.h, src/client/QXmppTrustMemoryStorage.cpp, src/client/QXmppTrustMemoryStorage.h, src/client/QXmppTrustStorage.cpp, src/client/QXmppTrustStorage.h, tests/qxmppatmmanager/tst_qxmppatmmanager.cpp, tests/qxmpptrustmemorystorage/tst_qxmpptrustmemorystorage.cpp
QXmppTrustStorage is now the base class for all trust storages used by
end-to-end encryption managers.
QXmppAtmTrustStorage is used by QXmppAtmManager.
QXmppTrustMemoryStorage is now the base class for all trust storages
that use the memory for storing data.
QXmppAtmTrustMemoryStorage can be used by QXmppAtmManager.
Methods needed by the upcoming OMEMO implementation are added.
Some existing methods are refactored.
=> Refactor trust storages

src/base/QXmppTrustMessages.cpp
=> TrustMessages: Use QStringLiteral

src/base/QXmppMessage.cpp, src/base/QXmppMessage.h, src/base/QXmppStanza.cpp, src/base/QXmppStanza.h, src/client/QXmppAtmManager.cpp, tests/qxmppatmmanager/tst_qxmppatmmanager.cpp, tests/qxmppmessage/tst_qxmppmessage.cpp, tests/qxmppstanza/tst_qxmppstanza.cpp
That class contains addtional data needed for end-to-end encryption purposes.
'senderKey' is moved from QXmppMessage to QXmppE2eeMetadata.
'sceTimestamp' is introduced.
=> Add QXmppE2eeMetadata used by QXmppStanza

src/client/QXmppUploadRequestManager.cpp
=> Fix some unsafety issues

src/client/QXmppAtmManager.cpp, tests/qxmppatmmanager/tst_qxmppatmmanager.cpp
=> AtmManager: Fix memory leaks in tests and apply clang-format

tests/qxmppatmmanager/tst_qxmppatmmanager.cpp
=> tests: AtmManager: Apply clang-format after replacing '->' with '.'

src/client/QXmppPubSubManager.cpp, src/client/QXmppPubSubManager.h, tests/qxmpppubsubmanager/tst_qxmpppubsubmanager.cpp
This fixes inconsistencies introduced by @LNJ's commits after https://github.com/qxmpp-project/qxmpp/pull/392#discussion_r846669515.
=> Fix PubSub methods with a standard item ID parameter

src/client/QXmppPubSubManager.h
=> PubSubManager: Fix template usage of 'requestItem()'

src/client/QXmppPubSubManager.cpp, src/client/QXmppPubSubManager.h, tests/qxmpppubsubmanager/tst_qxmpppubsubmanager.cpp
This is needed if the IDs of incoming items should be checked externally.
=> PubSubManager: Make 'standardItemIdToString()' public

src/base/QXmppMessage.cpp
=> Message: Do not allow XEP-0184 request and received element together

src/CMakeLists.txt
This header is used by program Kaidan at least.
=> cmake: add QXmppExtension.h to INSTALL_HEADER_FILES

src/client/QXmppCallStream.cpp
instead of deprecated one  when build with GStreamer >= 1.20.0
=> QXmppCallStream: use new GStreamer method

QXmppConfig.cmake.in
This way, users of the library don't need to find QtNetwork and QtXml themselves before finding QXmpp
PR check list:
=> Find dependencies dependencies of QXmpp when finding QXmpp

.github/pull_request_template.md, src/CMakeLists.txt, src/base/QXmppMessage.cpp, src/base/QXmppMessage.h, src/client/QXmppCarbonManager.cpp, src/client/QXmppCarbonManager.h, src/client/QXmppCarbonManagerV2.cpp, src/client/QXmppCarbonManagerV2.h, tests/qxmppcarbonmanager/tst_qxmppcarbonmanager.cpp
- Add new message carbons manager
- tests: CarbonManager: Also test manager v2 & refactor
- Message: Add isCarbonForwarded attribute
PR check list:
=> Add new e2ee capable carbon manager

src/omemo/OmemoLibWrappers.h
I don't know why this didn't happen before, but somehow my compiler
started trying to use the wrong constructor.
PR check list:
=> OmemoLibWrappers: Fix compilation

src/client/QXmppAtmTrustMemoryStorage.h, src/client/QXmppAttentionManager.cpp, src/client/QXmppAttentionManager.h, src/client/QXmppBookmarkManager.cpp, src/client/QXmppBookmarkManager.h, src/client/QXmppClient.cpp, src/client/QXmppClient.h, src/client/QXmppClientExtension.cpp, src/client/QXmppClientExtension.h, src/client/QXmppDiscoveryManager.cpp, src/client/QXmppDiscoveryManager.h, src/client/QXmppMucManager.cpp, src/client/QXmppMucManager.h, src/client/QXmppOutgoingClient.cpp, src/client/QXmppOutgoingClient.h, src/client/QXmppRegistrationManager.cpp, src/client/QXmppRegistrationManager.h, src/client/QXmppRosterManager.cpp, src/client/QXmppRosterManager.h, src/client/QXmppTransferManager.cpp, src/client/QXmppTransferManager.h, src/client/QXmppUploadRequestManager.cpp, src/client/QXmppUploadRequestManager.h, src/client/QXmppVCardManager.cpp, src/client/QXmppVCardManager.h, src/client/QXmppVersionManager.cpp, src/client/QXmppVersionManager.h
- Replace raw pointers by unique_ptr
- RegistrationManager: Replace QScopedPointer with unique_ptr
PR check list:
=> Use unique_ptrs

doc/xep.doc, src/CMakeLists.txt, src/base/QXmppConstants.cpp, src/base/QXmppConstants_p.h, src/base/QXmppHash.cpp, src/base/QXmppHash.h
Parsing and serialization for XEP-0300
https://xmpp.org/extensions/xep-0300.html in version 1.0.
PR check list:
=> Implement XEP-0300: Use of Cryptographic Hash Functions in XMPP

doc/xep.doc, src/CMakeLists.txt, src/base/QXmppConstants.cpp, src/base/QXmppConstants_p.h, src/base/QXmppThumbnail.cpp, src/base/QXmppThumbnail.h
XEP-0264: Jingle Content Thumbnails version 0.4.
https://xmpp.org/extensions/xep-0264.html
PR check list:
=> Implement XEP-0264: Jingle Content Thumbnails

doc/xep.doc, src/CMakeLists.txt, src/base/QXmppConstants.cpp, src/base/QXmppConstants_p.h, src/base/QXmppFileMetadata.cpp, src/base/QXmppFileMetadata.h, src/base/QXmppGlobal.h
- Add parsing and serialization for XEP-0446
- Add macros for defining all the different default constructors
PR check list:
=> Implement XEP-0446: File metadata element

src/base/QXmppFileMetadata.cpp, src/base/QXmppGlobal.h
=> Fix rule of six macro

doc/doap.xml, src/CMakeLists.txt, src/base/QXmppConstants.cpp, src/base/QXmppConstants_p.h, src/base/QXmppFileShare.cpp, src/base/QXmppFileShare.h, src/base/QXmppMessage.cpp, src/base/QXmppMessage.h, tests/qxmppmessage/tst_qxmppmessage.cpp
Implements parsing for the file sharing element from XEP-0447:
Stateless files sharing version 0.2.
https://xmpp.org/extensions/xep-0447.html
PR check list:
=> Implement XEP-0447: Stateless file sharing: File sharing element

src/CMakeLists.txt, src/base/QXmppFileShare.cpp, src/base/QXmppFileShare.h, src/base/QXmppHttpFileSource.cpp, src/base/QXmppHttpFileSource.h
Before just QUrl was used, which was okay. This should make it better
recognizable and it makes clear it is only used for HTTP urls.
PR check list:
=> Add extra class for HttpFileSource instead of using QUrl

src/base/QXmppBitsOfBinaryData.cpp, src/base/QXmppBitsOfBinaryData.h, tests/qxmppbitsofbinaryiq/tst_qxmppbitsofbinaryiq.cpp, tests/qxmpphttpuploadmanager/tst_qxmpphttpuploadmanager.cpp, tests/util.h
It automatically hashes the data and creates a content ID.
PR check list:
=> BitsOfBinaryData: Add fromByteArray() utility function

doc/doap.xml, src/CMakeLists.txt, src/base/QXmppConstants.cpp, src/base/QXmppConstants_p.h, src/base/QXmppEncryptedFileSource.cpp, src/base/QXmppEncryptedFileSource.h, src/base/QXmppEncryptedFileSource_p.h, src/base/QXmppHash.cpp, tests/qxmppmessage/tst_qxmppmessage.cpp
- esfs
- esfs: Implement parsing
- Implement serialization
- Add rule of six constructor
PR check list:
=> Implement XEP-0448: Encryption for stateless file sharing parsing

src/base/QXmppFileMetadata.cpp, src/base/QXmppFileMetadata.h
The standard actually allows multiple thumbnails.
PR check list:
=> FileMetadata: Allow multiple thumbnails

src/client/QXmppHttpUploadManager.cpp, src/client/QXmppHttpUploadManager.h
=> QXmppHttpUploadManager: Also use unique_ptr for data device

src/client/QXmppHttpFileSharingProvider.cpp
This is unfortunatly required for compatiblity with legacy clients, because they rely on the url to figure out the file type.
PR check list:
=> QXmppHttpFileSharingProvider: keep original filename when known

src/CMakeLists.txt
=> Fix installing the headers that are dependent on QCA

src/base/QXmppConstants.cpp, src/base/QXmppConstants_p.h, src/base/QXmppJingleIq.cpp
=> Clean up Jingle namespaces

tests/qxmppjingleiq/tst_qxmppjingleiq.cpp
=> tests: JingleIq: Fix comparison for 'uint32_t'

src/base/QXmppConstants.cpp, src/base/QXmppConstants_p.h, src/base/QXmppJingleIq.cpp, src/base/QXmppJingleIq.h, tests/qxmppjingleiq/tst_qxmppjingleiq.cpp
=> Implement XEP-0167: Jingle RTP Sessions error conditions

tests/qxmppcallmanager/tst_qxmppcallmanager.cpp, tests/travis/build-and-test
- Clean up CallManager test
- Skip call manager tests on macOS
PR check list:
=> skip call manager macos

src/client/QXmppE2eeExtension.cpp, src/client/QXmppE2eeExtension.h, src/client/QXmppMamManager.cpp, src/client/QXmppMamManager.h, src/omemo/QXmppOmemoManager.cpp, src/omemo/QXmppOmemoManager.h, tests/qxmppclient/tst_qxmppclient.cpp
- E2eeExtension: Add isEncrypted() and decryptMessage() functions
- OmemoManager: Implement isEncrypted() and decryptMessage()
- MamManager: Add future based interface with encryption support
PR check list:
=> Add future-based interface with encryption to MAM manager

src/client/QXmppClient.cpp, src/client/QXmppE2eeExtension.h, src/omemo/QXmppOmemoManager.cpp, src/omemo/QXmppOmemoManager_p.cpp
=> E2eeExtension: Return encrypted stanzas as Message/Iq instead of XML

tests/qxmppstreaminitiationiq/tst_qxmppstreaminitiationiq.cpp
=> tests: StreamInitiationIq: Fix usage of 'Q_SLOT' instead of 'slots:'

tests/qxmppdiscoverymanager/tst_qxmppdiscoverymanager.cpp
PR check list:
Removed unused variable in QXmppDiscoveryManager test.
=> Fix: remove unused variable

src/client/QXmppCarbonManagerV2.cpp
=> CarbonManagerV2: Fix enabling carbons

src/base/QXmppMamIq.h, src/base/QXmppPubSubIq_p.h, src/client/QXmppMamManager.h
=> Fix building Kaidan against QXmpp with MSVC 2019

CMakeLists.txt
PR check list:
This commit adds the ability to chose Qt Major Version from outside of the project.
The way it's written right now if a host have some Qt6 packages installed qxmpp automatically builds against Qt6 and there is no other way to affect it apart from patches ([read the comments here](https://aur.archlinux.org/packages/qxmpp))
The way I suggest it's going to change nothing by default but if someone is building qxmpp from other CMake project qxmpp is going to be build to the corresponding version of Qt of the parent project. This also is going to enable a way to quickly change Qt version with cmake build flags like `-D QT_MAJOR_VERSION=5` or `-D QT_MAJOR_VERSION=6`
=> Add an ability to chose Qt major version from outside of the project

src/base/QXmppMessage.cpp, tests/qxmppmessage/tst_qxmppmessage.cpp
Since QXmpp does not differentiate between different EME versions receiving clients support, it is better to always send the encryption name. It ensures that a name is displayed by the receiving client even if it does not support the latest EME version introducing a new encryption.
PR check list:
=> EME: Always send encryption name as fallback

src/base/QXmppStream.cpp
See https://xmpp.org/rfcs/rfc6120.html#stanzas-attributes-from-c2s point 3
PR check list:
=> Stream: Allow no 'from' attribute for IQ responses

src/base/QXmppMamIq.h, src/base/QXmppPubSubIq_p.h, src/client/QXmppMamManager.h
Fixes the Kaidan build with MSVC.
Weirdly enough, MSVC got confused on finding the matching overload for
<<, so I replaced it with push_back().
PR check list:
=> Fix missing exports with MSVC 2019

src/omemo/QXmppOmemoData.cpp, src/omemo/QXmppOmemoManager_p.cpp
I wrote the problematic code, so yay
PR check list:
=> QXmppOmemo: Fix ODR violation

src/client/QXmppMamManager.cpp
=> MamManager: Fix crash when reading .size() from a deleted QVector

CMakeLists.txt, qxmpp_legacy.pc.in
The include directory and link targets changed.
Also add a backward compatible pkgconfig file for Qt5 builds.
PR check list:
=> Fix the generated qxmpp pkgconfig files

src/omemo/CMakeLists.txt
This leads to "not found" warnings with -Wmissing-include-dirs but worse, it will one day lead to build errors when having different APIs in the installed headers and locally (after making changes)
PR check list:
=> Don't search for your headers in your install dir, when building the lib

src/client/QXmppClient.cpp, src/client/QXmppClient.h
=> Client: Add constructor that allows to create without extensions

src/omemo/QXmppOmemoManager_p.cpp
=> OmemoManager: Do not use a default fallback body for chat markers

.github/pull_request_template.md, .github/workflows/tests.yml, .gitignore, tests/travis/build-documentation
=> ci: Add doxygen job that is failing on warnings

doc/doap.xml, src/CMakeLists.txt, src/base/QXmppFallback.h, src/base/QXmppMessage.cpp, src/base/QXmppMessage.h, src/base/QXmppUtils.cpp, src/base/QXmppUtils_p.h, tests/qxmppmessage/tst_qxmppmessage.cpp
- **Utils: Add parseInt() allowing parsing of all common int types**
- **Update XEP-0428: Fallback Indication to v0.2**
PR check list:
=> Update XEP-0428: Fallback Indication to v0.2

src/omemo/QXmppOmemoManager.cpp
=> OmemoManager: Clarify that own key is not retrieved via 'keys()'

.clang-format, doc/doap.xml, src/CMakeLists.txt, src/base/Algorithms.h, src/base/QXmppConstants_p.h, src/base/QXmppSasl.cpp, src/base/QXmppSasl_p.h, src/base/QXmppUtils.cpp, src/base/QXmppUtils.h, src/base/QXmppUtils_p.h, src/base/StringLiterals.h, src/client/QXmppClient.cpp, src/client/QXmppClient.h, src/client/QXmppConfiguration.cpp, src/client/QXmppConfiguration.h, src/client/QXmppCredentials.h, src/client/QXmppOutgoingClient.cpp, src/client/QXmppOutgoingClient.h, src/client/QXmppOutgoingClient_p.h, src/client/QXmppSaslManager.cpp, src/client/QXmppSaslManager_p.h, src/server/QXmppIncomingClient.cpp, tests/qxmppclient/tst_qxmppclient.cpp, tests/qxmppsasl/tst_qxmppsasl.cpp, tests/util.h
=> FAST token-based authentication

.clang-format, src/base/QXmppMessage.cpp, src/base/QXmppMessage.h, src/client/QXmppHttpUploadManager.cpp, tests/qxmppaccountmigrationmanager/tst_qxmppaccountmigrationmanager.cpp, tests/qxmppmessage/tst_qxmppmessage.cpp
- **clang-format: Break before C++11 attributes**
- **Message: Allow multiple stanza IDs (XEP-0359)**
PR check list:
=> Message: Allow multiple stanza IDs

src/client/QXmppOutgoingClient.cpp, src/client/QXmppOutgoingClient_p.h
connectToHost() must be called after the previous connection has been
closed. This happens after the socket error is emitted.
=> Client: Fix connection if first SRV record fails

src/base/QXmppMessage.cpp, src/omemo/QXmppOmemoManager_p.cpp, tests/qxmppmessage/tst_qxmppmessage.cpp
- **Message: Serialize fallback markers in both public/private SCE mode**
- **OmemoManager: Remove private fallback markers before serializing**
PR check list:
**Funded by [NLnet](https://nlnet.nl/foundation/) via [NGI Assure](https://nlnet.nl/assure/).**
=> Message: Serialize fallback markers in both public and private modes

src/client/QXmppAccountMigrationManager.cpp, src/client/QXmppAccountMigrationManager.h
This is needed because without that change applications can not store and use app specific data. By example Kaidan export and import its roster settings which requires that all migration tasks finished before importing roster related data.
PR check list:
=> QXmppAccountMigrationManager: Make public the extensions getter/setter

src/client/QXmppRegistrationManager.cpp
=> RegistrationManager: Handle failing registration form request

src/client/QXmppMovedItem_p.h, src/client/QXmppMovedManager.cpp, src/client/QXmppMovedManager.h, tests/qxmppmovedmanager/tst_qxmppmovedmanager.cpp
- **MovedManager: Fix doxygen warnings**
- **MovedManager.h: Remove Client.h include**
- **tests: MovedManager: Fix ""_s literals with MSVC**
=> Fix moved doxygen warnings, windows ci

src/base/Algorithms.h, src/client/QXmppAccountMigrationManager.cpp, src/client/QXmppAccountMigrationManager.h, src/client/QXmppMixManager.cpp, src/client/QXmppRosterManager.cpp, src/client/QXmppRosterManager.h, tests/TestClient.h, tests/qxmppaccountmigrationmanager/tst_qxmppaccountmigrationmanager.cpp, tests/util.h
PR check list:
Fixed a bunch of issues in the QXmppAccountMigrationManager:
- Stabilized the unit tests moving from unordered to sorted keys nodes
- Handle correctly joining mix channels
=> Fix migration manager

src/client/QXmppMixManager.h, tests/qxmppmixmanager/tst_qxmppmixmanager.cpp
If no nodes were specified to be unsubscribed from for updateSubscriptions(), all enums were added to be unsubscribed from. That resulted in the same nodes being specified to be subcribed to and to be unsubscribed from.
PR check list:
=> MixManager: Fix behavior for updating node subscriptions

src/omemo/QXmppOmemoManager.cpp, src/omemo/QXmppOmemoManager_p.cpp
=> Fix OMEMO signed pre key pair renewal

LICENSES/MIT.txt, doc/doap.xml, src/CMakeLists.txt, src/base/QXmppColorGeneration.cpp, src/base/QXmppColorGeneration.h, src/base/hsluv/hsluv.c, src/base/hsluv/hsluv.h, tests/qxmppclient/tst_qxmppclient.cpp
- **Import hsluv-c code for consistent color generation**
- **Implement XEP-0392: Consistent Color Generation**
PR check list:
=> Implement XEP-0392: Consisten Color Generation

src/client/QXmppFileEncryption.cpp
m_cipher->ok() is to be called only after an explicit `update()` or `final()` call.
This changes fix the crash when attempting to upload encrypted files.
PR check list:
=> Qt 6: Fix crash when sending encrypted files

src/client/QXmppMixManager.cpp
=> Fix QXmppMixManager not finishing task when nothing to export

src/base/QXmppDataFormBase.h, src/base/QXmppFutureUtils_p.h, src/base/QXmppMessage.cpp, src/base/QXmppPubSubEvent.h, src/base/QXmppPubSubNodeConfig.cpp, src/base/QXmppRpcIq.cpp, src/client/QXmppEntityTimeManager.cpp, tests/qxmpppresence/tst_qxmpppresence.cpp, tests/qxmpppubsubevent/tst_qxmpppubsubevent.cpp, tests/qxmppsceenvelope/tst_qxmppsceenvelope.cpp, tests/qxmppstanza/tst_qxmppstanza.cpp, tests/util.h
- **Fix deprecations: Use QMetaType::Type instead of QVariant::Type**
- **Fix deprecations: Use std::as_const instead of qAsConst**
- **Fix deprecations: Use QTimeZone instead of Qt::TimeZone**
=> Fix Qt 6.9 deprecations

src/base/QXmppElement.cpp, src/base/Stream.cpp, src/client/QXmppInvokable.cpp, tests/qxmppstreamfeatures/tst_qxmppstreamfeatures.cpp, tests/util.h
- **Fix deprecations: QDomDocument::setContent(): Use new ParseOptions**
- **Fix deprecations: QMetaType::create/destroy()**
=> Fix deprecated QDomDocument::setContent, QMetaType

src/client/QXmppMovedManager.cpp, src/client/QXmppMovedManager.h, src/client/QXmppRosterManager.cpp, src/client/QXmppRosterManager.h, tests/qxmpprostermanager/tst_qxmpprostermanager.cpp
=> RosterManager: Fix notifying on subscription request with valid old JID
